### ISSUE TITLE
[Feature request]: Orientation Input while Marking Vertex

### ISSUE THREAD

**Issue by vignesh-katomaran** [open-rmf/rmf_traffic_editor#473]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

In RMF Traffic Editor we've only option to mark xy pose but orientation is not in use control, whenever the robot approaches the in between vertexes while navigation it rotating in default orientation but we need to give this as custom orientation. as well as it should also overwrite in between goals orientation towards the path.

**Comment by Yadunund** [comment]
If you wish to constrain your robot to a particular orientation when entering a lane, ie the robot should always drive forward or in reverse down a lane, you can set the `orientation` property of the lane. See our [documentation](https://osrf.github.io/ros2multirobotbook/traffic-editor.html#adding-a-traffic-lane). 

Goal orientation is a task specific property and can be specified when constructing your task definition. You can set it [here](https://github.com/open-rmf/rmf_ros2/blob/4a85f27f412bfcf203fa21ca7b332d798e1d63a5/rmf_fleet_adapter/schemas/place.json#L14) and see [this example](https://github.com/open-rmf/rmf_demos/blob/main/rmf_demos_tasks/rmf_demos_tasks/dispatch_patrol.py) of submitting such a task. 

I'll close this issue as the requested features/capabilities already exist imo. But feel free to reopen if you feel otherwise.
